export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE= 'LOGIN_FAILURE'
export const LOGOUT= 'LOGOUT'
export const UPDATE_STATE= 'UPDATE_STATE'
export const SEARCH_RESULT = 'SEARCH_RESULT'
export const SEARCH_TAB = "SEARCH_TAB"